export const answers = {
    response1 : "Use ChatGPT efficiently. You can write C# code, Java Code, Python, Dataflows. Blah blah blah",
    response2 : "I use Copilot regularly. Drew uses ChatGPT efficiently. You see this resume it can summarize it. ChatGPT! ChatGPT!",
    response3 : "Microsoft is following this, we should also follow that. ChatGPT is nice. Use all AI tools. I am going to conduct a survey",
    resposne4 : "All the code is 80% generated by AI by a professional developer. Very professional practices. Use ChatGPT Haha. I also use ChatGPT while taking a bath"
}